spring:
  data:
    mongodb:
      auto-index-creation: true
  application:
    name: example
  datasource:
    primary:
      hikari:
        jdbc-url: jdbc:postgresql://localhost:5432/sezdb
        username: andruf
        password: andruf
        driver-class-name: org.postgresql.Driver
        connection-timeout: 2000
        maximum-pool-size: 10
    replica:
      hikari:
        jdbc-url: jdbc:postgresql://localhost:5433/sezdb
        username: andruf
        password: andruf
        driver-class-name: org.postgresql.Driver
        connection-timeout: 2000
        maximum-pool-size: 10
  docker:
    compose:
      file: /home/andruf/Work/IdeaProjects/example/example/docker-compose.yaml
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    clean-disabled: false
app:
  repository.type: jpa